---
- name: install nginx
  homebrew:
    name: nginx
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install nginx
  pacman:
    name: nginx-mainline
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'
