---
- name: install nginx
  homebrew:
    name: nginx
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install nginx
  pacman:
    name: nginx-mainline
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'

- block:

    - name: add nginx ppa
      apt_repository:
        repo: 'ppa:nginx/stable'
        state: present
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

  when: ansible_distribution == 'Ubuntu'
  become: yes
  become_method: sudo
