---
- name: install vlc
  homebrew_cask:
    name: vlc
    state: latest
  when: ansible_os_family == 'Darwin'

- block:

    - name: install codecs
      pacman:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - a52dec
        - faac
        - faad2
        - flac
        - jasper
        - lame
        - libdca
        - libdv
        - libmad
        - libmpeg2
        - libtheora
        - libvorbis
        - libxv
        - wavpack
        - x264
        - xvidcore
      become: yes
      become_method: sudo

    - name: install vlc
      pacman:
        name: vlc
        update_cache: yes
      become: yes
      become_method: sudo

  when: ansible_os_family == 'Archlinux'
