---
- name: create bashrc.d folder
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory

- block:

    - name: install bash
      homebrew:
        name: bash
        state: latest

    - name: setup bashrc
      template:
        src: "bashrc.mac.bash"
        dest: "{{ ansible_env.HOME }}/.bashrc"

    - name: setup bash_profile
      copy:
        src: bash_profile.mac.bash
        dest: "{{ ansible_env.HOME }}/.bash_profile"

    - name: setup bash completion
      copy:
        src: "bash_completion.mac.bash"
        dest: "{{ ansible_env.HOME }}/.bashrc.d/bash_completion.bash"

  when: ansible_os_family == 'Darwin'

- block:

    - name: install bash
      pacman:
        name: bash
        state: latest
        update_cache: yes
      become: yes
      become_method: sudo

    - name: setup bashrc
      template:
        src: "bashrc.arch.bash"
        dest: "{{ ansible_env.HOME }}/.bashrc"

    - name: setup bash completion
      copy:
        src: "bash_completion.arch.bash"
        dest: "{{ ansible_env.HOME }}/.bashrc.d/bash_completion.bash"

  when: ansible_os_family == 'Archlinux'

- name: copy bashrc.d files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.bashrc.d/{{ item }}"
  with_items:
    - ansible.bash
    - prompt.bash
    - travis.bash
