---
- name: create bashrc.d folder
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory

- block:

    - name: install bash
      homebrew:
        name: bash
        state: latest

    - name: Add path to /etc/shells
      blockinfile:
        path: /etc/shells
        block: |
          {{ homebrew_path }}/bin/bash
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      become: yes
      become_method: sudo

    - name: setup bashrc
      template:
        src: "bashrc.mac.bash"
        dest: "{{ ansible_env.HOME }}/.bashrc"

    - name: setup bash_profile
      copy:
        src: bash_profile.mac.bash
        dest: "{{ ansible_env.HOME }}/.bash_profile"

    - name: setup bash completion
      copy:
        src: "bash_completion.mac.bash"
        dest: "{{ ansible_env.HOME }}/.bashrc.d/bash_completion.bash"

    - name: add brew bash to shells
      command: "echo {{ homebrew_path }}/bin/bash >> /etc/shells"
      become: yes
      become_method: sudo

    - name: set shell for user
      command: "chsh -s {{ homebrew_path }}/bin/bash"

  when: ansible_os_family == 'Darwin'

- name: install bash
  pacman:
    name: bash
    state: latest
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'

- name: install bash
  apt:
    name: bash
    state: latest
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'

- name: setup bashrc
  template:
    src: "bashrc.linux.bash"
    dest: "{{ ansible_env.HOME }}/.bashrc"
  when: ansible_os_family == 'Archlinux' or ansible_distribution == 'Ubuntu'

- name: setup bash completion
  copy:
    src: "bash_completion.linux.bash"
    dest: "{{ ansible_env.HOME }}/.bashrc.d/bash_completion.bash"
  when: ansible_os_family == 'Archlinux' or ansible_distribution == 'Ubuntu'

- name: copy bashrc.d files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.bashrc.d/{{ item }}"
  with_items:
    - ansible.bash
    - prompt.bash
