---
- block:

    - name: set hostname
      command: "scutil --set HostName {{ hostname }}"

    - name: set local hostname
      command: "scutil --set LocalHostName {{ hostname }}"

    - name: set computer name
      command: "scutil --set ComputerName {{ hostname }}"

    - name: flush dns cache
      command: dscacheutil -flushcache

  become: yes
  become_method: sudo
  when: ansible_os_family == 'Darwin'
