---
- name: make sure bashrc.d folder is present
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
  when: shell == 'bash'
  tags: shell

- name: make sure zshrc.d folder is present
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.d"
    state: directory
  when: shell == 'zsh'
  tags: shell

- block:

    - name: download install.sh
      get_url:
        url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
        dest: /tmp/nvm-install.sh
        mode: 0755

    - name: install nvm
      command: /tmp/nvm-install.sh

    - name: setup bash configs
      copy:
        src: nvm.bash
        dest: "{{ ansible_env.HOME }}/.bashrc.d/nvm.bash"
      when: shell == 'bash'
      tags: shell

    - name: setup zsh configs
      copy:
        src: nvm.zsh
        dest: "{{ ansible_env.HOME }}/.zshrc.d/nvm.zsh"
      when: shell == 'zsh'
      tags: shell

  when: ansible_os_family == 'Darwin'

- name: install nvm
  command: yaourt -S nvm --noconfirm
  when: ansible_os_family == 'Archlinux'

- block:

    - name: download install.sh
      get_url:
        url: https://raw.githubusercontent.com/creationix/nvm/v0.33.4/install.sh
        dest: /tmp/nvm-install.sh
        mode: 0755

    - name: install nvm
      command: /tmp/nvm-install.sh

  when: ansible_distribution == 'Ubuntu'

- name: setup bash configs
  copy:
    src: nvm.bash
    dest: "{{ ansible_env.HOME }}/.bashrc.d/nvm.bash"
  when: ansible_os_family == 'Archlinux' or ansible_distribution == 'Ubuntu'
