---
- name: install nvm
  homebrew:
    name: nvm
    state: latest
  when: ansible_os_family == 'Darwin'

- name: setup bash configs
  copy:
    src: nvm.mac.bash
    dest: "{{ ansible_env.HOME }}/.bashrc.d/nvm.mac.bash"
  when: ansible_os_family == 'Darwin'

- name: install nvm
  command: yaourt -S nvm --noconfirm
  when: ansible_os_family == 'Archlinux'

- name: setup bash configs
  copy:
    src: nvm.arch.bash
    dest: "{{ ansible_env.HOME }}/.bashrc.d/nvm.arch.bash"
  when: ansible_os_family == 'Archlinux'
