---
- name: make sure bashrc.d folder is present
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory

- block:

    - name: install nvm
      homebrew:
        name: nvm
        state: latest

    - name: setup bash configs
      copy:
        src: nvm.mac.bash
        dest: "{{ ansible_env.HOME }}/.bashrc.d/nvm.bash"

  when: ansible_os_family == 'Darwin'

- block:

    - name: install nvm
      command: yaourt -S nvm --noconfirm

    - name: setup bash configs
      copy:
        src: nvm.arch.bash
        dest: "{{ ansible_env.HOME }}/.bashrc.d/nvm.bash"

  when: ansible_os_family == 'Archlinux'
