---
- hosts: local
  connection: local
  roles:
    - { role: arch-setup, tags: setup, when: "ansible_os_family == 'Archlinux'" }
    - { role: git, tags: git }
    - { role: ssh, tags: ssh }
    - { role: brew, tags: brew, when: "ansible_os_family == 'Darwin'" }
    - { role: cask, tags: cask, when: "ansible_os_family == 'Darwin'" }
    - { role: mas, tags: mas, when: "ansible_os_family == 'Darwin'" }
    - { role: bash, tags: bash }
    - { role: git-radar, tags: git-radar }
    - { role: bash_aliases, tags: bash_aliases }
    - { role: gpg, tags: gpg }
    - { role: rc-files, tags: rc-files }
    - { role: vscode, tags: vscode }
    - { role: tig, tags: tig }
    - { role: nginx, tags: nginx }
    - { role: google-chrome, tags: google-chrome }
    - { role: vhosts, tags: vhosts }
    - { role: rbenv, tags: rbenv }
    - { role: dropbox, tags: dropbox }
    - { role: spotify, tags: spotify }
    - { role: vlc, tags: vlc }
    - { role: nvm, tags: nvm }
    # - { role: postgres, tags: postgres }
    # - { role: redis, tags: redis }
    # - { role: terraform, tags: terraform }
    # - { role: docker, tags: docker }
    # - { role: go, tags: go }
    # - { role: shellcheck, tags: shellcheck }
    # - { role: wkhtmltopdf, tags: wkhtmltopdf }
