cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'git'
brew 'mas'
brew 'go'
brew 'forego'
brew 'gpg'
brew 'tig'
brew 'heroku'
brew 'awscli'
brew 'rbenv'
brew 'terraform'
brew 'bash-completion'
brew 'ansible'
brew 'hub'
brew 'postgres', restart_service: true
brew 'redis', restart_service: true
brew 'michaeldfallen/formula/git-radar'
cask 'wkhtmltopdf'
cask '1password'
cask 'spectacle'
cask 'postman'
cask 'postico'
cask 'dropbox'
cask 'colorsnapper'
cask 'colorsnapper'
cask 'google-chrome'
cask 'sublime-text'
cask 'slack'
cask 'iterm2'
cask 'spotify'
cask 'alfred'
cask 'flux'
cask 'istat-menus'
cask 'virtualbox'
cask 'gpgtools'
cask 'imageoptim'
