---
- block:

    - name: install visual-studio-code
      homebrew_cask:
        name: visual-studio-code
        state: latest
        accept_external_apps: True

    - name: Setup Dir
      file:
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User"
        state: directory

    - name: Setup Files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - keybindings.json

    - name: Setup Templates
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - settings.json
        - projects.json

  when: ansible_os_family == 'Darwin'

- block:

    - name: install visual-studio-code
      command: yaourt -S visual-studio-code-bin --noconfirm
      when: ansible_os_family == 'Archlinux'

    - name: install visual-studio-code
      apt:
        deb: https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
      when: ansible_distribution == 'Ubuntu'

    - name: setup config dir
      file:
        path: "{{ ansible_env.HOME }}/.config/Code/User"
        state: directory

    - name: setup Templates
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/.config/Code/User/{{ item }}"
      with_items:
        - settings.json
        - projects.json

  when: ansible_os_family == 'Archlinux' or ansible_distribution == 'Ubuntu'

- name: install extensions
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
