---
- block:

    - name: install visual-studio-code
      homebrew_cask: name=visual-studio-code state=present

    - name: Setup Files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - keybindings.json

    - name: Setup Templates
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - settings.json
        - projects.json

  when: ansible_os_family == 'Darwin'

- name: install extensions
  shell: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
