---
- block:

    - name: install visual-studio-code
      homebrew_cask: name=visual-studio-code state=present

    - name: Setup Settings
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - settings.json
        - keybindings.json

    - name: Projects Setup
      template:
        src: projects.json.j2
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/projects.json"

  when: ansible_os_family == 'Darwin'

- name: install extensions
  shell: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
