---
- block:

    - name: install visual-studio-code
      homebrew_cask:
        name: visual-studio-code
        state: latest

    - name: Setup Files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - keybindings.json

    - name: Setup Templates
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item }}"
      with_items:
        - settings.json
        - projects.json

  when: ansible_os_family == 'Darwin'

- block:

    - name: install visual-studio-code
      command: yaourt -S visual-studio-code-bin --noconfirm

    - name: setup config dir
      file:
        path: "{{ ansible_env.HOME }}/.config/Code/User"
        state: directory

    - name: setup Templates
      template:
        src: "{{ item }}.j2"
        dest: "{{ ansible_env.HOME }}/.config/Code/User/{{ item }}"
      with_items:
        - settings.json
        - projects.json

  when: ansible_os_family == 'Archlinux'

- name: install extensions
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
