---
- name: download forego
  homebrew:
    name: forego
    state: latest
  when: ansible_os_family == 'Darwin'

- unarchive:
    src: https://bin.equinox.io/c/ekMN3bCZFUn/forego-stable-darwin-amd64.zip
    dest: /usr/local/bin/
    remote_src: True
    creates: /usr/local/bin/forego
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu' or ansible_os_family == 'Archlinux'
