---
- name: set dark menu bar
  command: osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to yes'

- name: set dock size
  command: defaults write com.apple.dock tilesize -int 40
  notify:
    - restart dock

- name: fix dock size
  command: defaults write com.apple.dock size-immutable -bool true
  notify:
    - restart dock

# - name: fix dock content
#   command: defaults write com.apple.dock contents-immutable -bool true
#   notify:
#     - restart dock

- name: set dock position
  command: defaults write com.apple.dock orientation -string right
  notify:
    - restart dock

- name: fix dock position
  command: defaults write com.apple.dock position-immutable -bool true
  notify:
    - restart dock
