---
- name: install tig
  homebrew:
    name: tig
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install tig
  pacman:
    name: tig
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'

- name: install tig
  apt:
    name: tig
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'

- name: copy tigrc
  copy:
    src: "tigrc"
    dest: "{{ ansible_env.HOME }}/.tigrc"
