---

- name: make sure bashrc.d folder is present
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
  when: shell == 'bash'
  tags: shell

- name: make sure zshrc.d folder is present
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.d"
    state: directory
  when: shell == 'zsh'
  tags: shell

- block:

    - name: install asdf
      homebrew:
        name: asdf
        state: latest

    - name: setup bash config
      copy:
        src: asdf.mac.bash
        dest: "{{ ansible_env.HOME }}/.bashrc.d/asdf.bash"
      when: shell == 'bash'
      tags: shell

    - name: setup zsh config
      copy:
        src: asdf.mac.zsh
        dest: "{{ ansible_env.HOME }}/.zshrc.d/asdf.zsh"
      when: shell == 'zsh'
      tags: shell

  when: ansible_os_family == 'Darwin'

- block:

    - name: install asdf
      command: yaourt -S asdf --noconfirm

  when: ansible_os_family == 'Archlinux'

- block:

    - name: install asdf
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "{{ ansible_env.HOME }}/.asdf"
        update: true
        force: true

  when: ansible_distribution == 'Ubuntu'

- block:

    - name: setup bash config
      copy:
        src: asdf.linux.bash
        dest: "{{ ansible_env.HOME }}/.bashrc.d/asdf.bash"
      when: shell == 'bash'
      tags: shell

    - name: setup zsh config
      copy:
        src: asdf.linux.zsh
        dest: "{{ ansible_env.HOME }}/.zshrc.d/asdf.zsh"
      when: shell == 'zsh'
      tags: shell

  when: ansible_distribution == 'Ubuntu' or ansible_os_family == 'Archlinux'
