---
- name: create zshrc.d folder
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.d"
    state: directory

- block:
    - name: install zsh
      homebrew:
        name: zsh
        state: latest

    - name: install zplug
      homebrew:
        name: zplug
        state: latest

    - name: Add path to /etc/shells
      blockinfile:
        path: /etc/shells
        block: |
          {{ homebrew_path }}/bin/zsh
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      become: yes
      become_method: sudo

    - name: setup zshrc
      template:
        src: "zshrc.j2"
        dest: "{{ ansible_env.HOME }}/.zshrc"

    - name: setup p10k.zsh
      copy:
        src: "p10k.zsh"
        dest: "{{ ansible_env.HOME }}/.p10k.zsh"

    - name: set shell for user
      command: "chsh -s {{ homebrew_path }}/bin/zsh"

  when: ansible_os_family == 'Darwin'

- name: copy zshrc.d files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.zshrc.d/{{ item }}"
  with_items:
    - ansible.zsh
    - android.zsh
    - alias.zsh
