---
- name: install git
  homebrew:
    name: git
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install git
  pacman:
    name: git
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Archlinux'

- name: copy files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  with_items:
    - .gitignore_global
    - .gitmessage.txt

- name: copy gitconfig
  template:
    src: ".gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
