---
- block:

    - name: Install Atom (OS X)
      homebrew_cask: name=atom state=present

    - name: Check installed atom packages
      shell: "apm list --installed --bare | sed 's/@.*//'"
      register: installed_atom_packages
      changed_when: false

    - name: Install Atom packages
      command: apm install {{ item }}
      when: item not in installed_atom_packages.stdout
      with_items: "{{ atom_packages }}"

    - name: Install APM Bash Completion
      homebrew: name=apm-bash-completion state=present

  when: ansible_os_family == 'Darwin'

- name: setup config files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.atom/{{ item }}"
  with_items:
    - config.cson
    - init.coffee
    - keymap.cson
    - snippets.cson
    - styles.less
