---
- name: install git-radar
  homebrew:
    name: michaeldfallen/formula/git-radar
    state: latest
  when: ansible_os_family == 'Darwin'

- block:

    - name: install git-radar
      git:
        repo: https://github.com/michaeldfallen/git-radar
        dest: "{{ ansible_env.HOME }}/.git-radar"

    - name: make sure bashrc.d folder is present
      file:
        path: "{{ ansible_env.HOME }}/.bashrc.d"
        state: directory

    - name: setup for bash
      copy:
        src: git-radar.bash
        dest: "{{ ansible_env.HOME }}/.bashrc.d/git-radar.bash"

  when: ansible_os_family == 'Archlinux' or ansible_distribution == 'Ubuntu'
