---
- name: install git-radar
  homebrew:
    name: michaeldfallen/formula/git-radar
    state: latest
  when: ansible_os_family == 'Darwin'

- block:

    - name: install git-radar
      git:
        repo: https://github.com/michaeldfallen/git-radar
        dest: "{{ ansible_env.HOME }}/.git-radar"

    - name: make sure bashrc.d folder is present
      file:
        path: "{{ ansible_env.HOME }}/.bashrc.d"
        state: directory
      when: shell == 'bash'
      tags: shell

    - name: make sure zshrc.d folder is present
      file:
        path: "{{ ansible_env.HOME }}/.zshrc.d"
        state: directory
      when: shell == 'zsh'
      tags: shell

    - name: setup for bash
      copy:
        src: git-radar.bash
        dest: "{{ ansible_env.HOME }}/.bashrc.d/git-radar.bash"
      when: shell == 'bash'
      tags: shell

    - name: setup for zsh
      copy:
        src: git-radar.zsh
        dest: "{{ ansible_env.HOME }}/.zshrc.d/git-radar.zsh"
      when: shell == 'zsh'
      tags: shell

  when: ansible_os_family == 'Archlinux' or ansible_distribution == 'Ubuntu'
