---
- name: install go
  homebrew:
    name: go
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install go
  pacman:
    name: go
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'

- name: install go
  apt:
    name: golang-go
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'

- name: make sure bashrc.d folder is present
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    state: directory
  when: shell == 'bash'
  tags: shell

- name: make sure zshrc.d folder is present
  file:
    path: "{{ ansible_env.HOME }}/.zshrc.d"
    state: directory
  when: shell == 'zsh'
  tags: shell

- name: setup bash config
  copy:
    src: "go.bash"
    dest: "{{ ansible_env.HOME }}/.bashrc.d/go.bash"
  when: shell == 'bash'
  tags: shell

- name: setup bash config
  copy:
    src: "go.zsh"
    dest: "{{ ansible_env.HOME }}/.zshrc.d/go.zsh"
  when: shell == 'zsh'
  tags: shell
