---
- name: install terraform
  homebrew:
    name: terraform
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install terraform
  pacman:
    name: terraform
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'

- unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
    dest: "{{ homebrew_bin_path }}/"
    remote_src: True
    creates: "{{ homebrew_bin_path }}/terraform"
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
