---
- name: install terraform
  homebrew:
    name: terraform
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install terraform
  pacman:
    name: terraform
    update_cache: yes
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'
