---
- block:

    - name: add hh repo
      apt_repository:
        repo: ppa:ultradvorka/ppa
        state: present
        update_cache: yes

    - name: install hh
      apt:
        name: hh
        update_cache: yes
        state: latest

    - name: make sure bashrc.d folder is present
      file:
        path: "{{ ansible_env.HOME }}/.bashrc.d"
        state: directory

    - name: setup bash config
      copy:
        src: "hh.bash"
        dest: "{{ ansible_env.HOME }}/.bashrc.d/hh.bash"

  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
