---
- name: install skype
  homebrew_cask:
    name: skype
    state: latest
    accept_external_apps: True
  when: ansible_os_family == 'Darwin'

- name: install skype
  command: yaourt -S skypeforlinux-stable-bin --noconfirm
  when: ansible_os_family == 'Archlinux'

- name: install skype
  apt:
    deb: https://repo.skype.com/latest/skypeforlinux-64.deb
    state: present
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
