---
- block:

    - name: Install Subblime (OS X)
      homebrew_cask: name=sublime-text state=present

    - name: setup config files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Packages/User/{{ item }}"
      with_items:
        - Package Control.sublime-settings
        - Preferences.sublime-settings
        - JavaScript (Babel).sublime-settings
        - JavaScript.sublime-settings
        - JsPrettier.sublime-settings
        - Markdown.sublime-settings
        - GoSublime.sublime-settings
        - Ruby.sublime-settings
        - SublimeLinter.sublime-settings

  when: ansible_os_family == 'Darwin'
