---
- name: restart nginx homebrew
  command: brew services restart nginx
  become: yes
  become_method: sudo

- name: restart nginx systemctl
  command: systemctl restart nginx
  become: yes
  become_method: sudo

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
  become_method: sudo
