---
- name: install gnupg
  homebrew:
    name: gnupg
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install gnupg
  pacman:
    name: gnupg
    state: latest
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'

- name: setup gpg dir
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory

- name: setup gpg conf
  template:
    src: gpg.conf.j2
    dest: "{{ ansible_env.HOME }}/.gnupg/gpg.conf"

- name: setup gnupg bash
  copy:
    src: gnupg.bash
    dest: "{{ ansible_env.HOME }}/.bashrc.d/gnupg.bash"
