---
- name: install postgres
  homebrew:
    name: postgres
    state: present
  when: ansible_os_family == 'Darwin'

- block:

    - name: install postgres
      pacman:
        name: postgresql
        update_cache: yes
        state: present
      become: yes
      become_method: sudo

    - name: create postgres dir
      file:
        path: "/var/lib/postgres"
        state: directory
        owner: postgres
        group: postgres
      become: yes
      become_method: sudo

    - name: create postgres data dirs
      file:
        path: "/var/lib/postgres/data"
        state: directory
        owner: postgres
        group: postgres
      become: yes
      become_method: sudo

    - name: check if postgres data is present
      stat:
        path: /var/lib/postgres/data/postgresql.conf
      register: postgres_data_present
      changed_when: false
      become: yes
      become_method: sudo

    - name: setup base db
      command: initdb -D '/var/lib/postgres/data'
      when: postgres_data_present.stat.exists == False
      become: yes
      become_user: postgres

    - name: start and enable postgres
      systemd:
        name: postgresql
        state: started
        enabled: yes
      become: yes
      become_method: sudo

  when: ansible_os_family == 'Archlinux'


- block:

    - name: install postgres
      apt:
        pkg: "postgresql"
        state: present

    - name: install additional packages
      apt:
        pkg: "{{ item }}"
        state: installed
        update-cache: yes
      with_items:
        - postgresql-contrib
        - python-psycopg2

    - name: start postgres
      service:
        name: postgresql
        state: started

  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'
