---
- name: install neovim
  homebrew:
    name: neovim/neovim/neovim
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install neovim
  pacman:
    name: neovim
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Archlinux'

- name: create config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory

- name: copy initial config
  copy:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
