---
- name: create config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory

- name: copy initial config
  copy:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: create autoload dir
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/autoload"
    state: directory

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/plug.vim"

- name: install neovim
  homebrew:
    name: neovim/neovim/neovim
    state: latest
  when: ansible_os_family == 'Darwin'

- name: install neovim
  pacman:
    name: neovim
    state: latest
    update_cache: yes
  become: yes
  become_method: sudo
  when: ansible_os_family == 'Archlinux'

