---
- block:

    - name: full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes
      become_method: sudo

    - name: install dev tools
      pacman:
        name: base-devel
        update_cache: yes
      become: yes
      become_method: sudo

    - name: install yaourt
      pacman:
        name: yaourt
        update_cache: yes
      become: yes
      become_method: sudo

    - name: install tools
      pacman:
        name:
          - p7zip
          - unrar
          - tar
          - rsync
          - conky
        update_cache: yes
      become: yes
      become_method: sudo

    - name: install themes
      command: yaourt -S paper-icon-theme-git materia-theme --noconfirm

    - name: update yaourt
      command: yaourt -Syua --noconfirm

  when: ansible_os_family == 'Archlinux'

- block:

    - name: add icon set ppa
      apt_repository:
        repo: ppa:snwh/pulp
        state: present
        update_cache: yes

    - name: install icon set
      apt:
        name: paper-icon-theme
        state: latest
        update_cache: yes

    - name: install tools
      apt:
        name:
          - curl
          - rsync
        state: latest
        update_cache: yes
      become: yes
      become_method: sudo

    - name: install gnome tools
      apt:
        name:
          - gnome-tweak-tool
          - breeze-cursor-theme
        state: latest
        update_cache: yes

    - name: copy login wallpaper
      copy:
        src: login-wallpaper.jpg
        dest: "/usr/share/backgrounds/login-wallpaper.jpg"

    - name: install gnome-shell styles
      copy:
        src: "ubuntu.css"
        dest: "/usr/share/gnome-shell/theme/ubuntu.css"
      tags: styles
      notify:
        - restart gnome-shell

  become: yes
  become_method: sudo
  when: ansible_distribution == 'Ubuntu'

- name: set interface settings
  command: "gsettings set org.gnome.desktop.interface {{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'gtk-theme', value: 'Adwaita-dark' }
    - { key: 'icon-theme', value: 'Paper' }
    - { key: 'cursor-theme', value: 'breeze_cursors' }
    - { key: 'clock-show-date', value: 'true' }
    - { key: 'show-battery-percentage', value: 'true' }

- name: hide desktop icons
  command: gsettings set org.gnome.desktop.background show-desktop-icons false

- name: set dash-to-dock settings
  command: "gsettings set org.gnome.shell.extensions.dash-to-dock {{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'extend-height', value: 'false' }
    - { key: 'apply-custom-theme', value: 'false' }
    - { key: 'dash-max-icon-size', value: '48' }
    - { key: 'background-opacity', value: '0.0' }
    - { key: 'transparency-mode', value: 'FIXED' }
    - { key: 'custom-theme-shrink', value: 'true' }
    - { key: 'icon-size-fixed', value: 'true' }
    - { key: 'dock-position', value: 'RIGHT' }
    - { key: 'running-indicator-style', value: 'DEFAULT' }

- name: set terminal settings
  command: "gsettings set org.gnome.Terminal.Legacy.Settings {{ item.key }} {{ item.value }}"
  with_items:
    - { key: 'default-show-menubar', value: 'false' }
    - { key: 'new-terminal-mode', value: 'tab' }

- name: set favorites
  command: gsettings set org.gnome.shell favorite-apps "['org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop']"

- name: copy terminal script
  command: gsettings set org.gnome.shell favorite-apps "['org.gnome.Terminal.desktop', 'org.gnome.Nautilus.desktop']"

- name: setup terminal-profile script
  copy:
    src: terminal-profile.sh
    dest: "{{ ansible_env.HOME }}/.terminal-profile.sh"
    mode: u+rwx
  tags: terminal-profile

- name: add profile
  copy:
    src: profile.conf
    dest: "{{ ansible_env.HOME }}/.profile.conf"
  tags: terminal-profile

- name: import profile
  command: "{{ ansible_env.HOME }}/.terminal-profile.sh import {{ ansible_env.HOME }}/.profile.conf"
  tags: terminal-profile
